server:
  port: 3001
  serverEnvironment: development

db:
  type: 'postgres'
  port: 5433
  database: 'supermovies'
  host: 'localhost'
  username: 'supermovies'
  password: 'supermovies'
  synchronize: false

jwt:
  expiresIn: 3600
  secret: 'topSecret1337'

settings:
  path: 'http://localhost:3000/'
